development:
  adapter: mysql
  database: demo_dev
  username: root
  password: 
  host: 127.0.0.1

test:
  adapter: mysql
  database: demo_test
  username: root
  password: 
  host: 127.0.0.1

production:
  adapter: mysql
  database: demo
  username: root
  password: 
  host: 127.0.0.1
